source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'EEG101' do
  use_frameworks!
  
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket'
  ]
  
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'react-native-torch', :path => '../node_modules/react-native-torch'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  target 'EEG101Tests' do
    inherit! :search_paths
    
    # Pods for testing
    
  end
end

post_install do |installer|
  system("sed -i '' 's#<fishhook/fishhook.h>#\"fishhook.h\"#g' ../node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m")
end
