// constants.js
// Constants used in Redux actions

module.exports = {
	SET_CONNECTION_STATUS: 'SET_CONNECTION_STATUS',
	SET_GRAPHVIEW_DIMENSIONS: 'SET_GRAPHVIEW_DIMENSIONS',
	SET_BCI_ACTION: 'SET_BCI_ACTION',
	SET_OFFLINE_MODE: 'SET_OFFLINE_MODE',
	SET_MENU: 'SET_MENU',
	SET_MUSE_INFO: 'SET_MUSE_INFO',
  SET_AVAILABLE_MUSES: 'SET_AVAILABLE_MUSES',
	SET_NOTCH_FREQUENCY: 'SET_NOTCH_FREQUENCY',
	SET_NOISE: 'SET_NOISE',
	UPDATE_CLASSIFIER_DATA: 'UPDATE_CLASSIFIER_DATA',
	SET_NATIVE_EMITTER: 'SET_NATIVE_EMITTER',
	START_BCI_RUNNING: 'START_BCI_RUNNING',
	STOP_BCI_RUNNING: 'STOP_BCI_RUNNING',
  	SET_BATTERY_VALUE: 'SET_BATTERY_VALUE'
}
