// constants.js
// Constants used in Redux actions

module.exports = {
	SET_CONNECTION_STATUS: 'SET_CONNECTION_STATUS',
	SET_GRAPHVIEW_DIMENSIONS: 'SET_GRAPHVIEW_DIMENSIONS',
	SET_BCI_ACTION: 'SET_BCI_ACTION',
	SET_OFFLINE_MODE: 'SET_OFFLINE_MODE',
	SET_MENU: 'SET_MENU',
}
