// constants.js
// Constants used in Redux actions

module.exports = {
	SET_CONNECTION_STATUS: 'SET_CONNECTION_STATUS',
	SET_GRAPHVIEW_DIMENSIONS: 'SET_GRAPHVIEW_DIMENSIONS',
	SET_BCI_ACTION: 'SET_BCI_ACTION',
}
