// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * @file
 * Represents data mapping in 'values' array in Accelerometer packet
 */
typedef NS_ENUM(NSInteger, IXNAccelerometer)
{
    /** Forward/Backward axis value in milliG */
    IXNAccelerometerForwardBackward,
    /** Up/Down axis value in milliG */
    IXNAccelerometerUpDown,
    /** Left/Right axis value in milliG */
    IXNAccelerometerLeftRight,
    IXNAccelerometerCount,
};
