// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from muse_file.djinni

#import "IXNAnnotationFormat.h"
#import <Foundation/Foundation.h>

/** Data struct corresponds to message Annotation in Muse protobuf schema. */

@interface IXNAnnotationData : NSObject
- (id)initWithAnnotationData:(IXNAnnotationData *)annotationData;
- (id)initWithData:(NSString *)data format:(IXNAnnotationFormat)format eventType:(NSString *)eventType eventId:(NSString *)eventId parentId:(NSString *)parentId;

/**
 * This is additional data for the event, can be in any format specified
 * by the Format enum.
 */
@property (nonatomic, readonly) NSString *data;

/** This specifies the string format of event_data. */
@property (nonatomic, readonly) IXNAnnotationFormat format;

/** This can be used to classify events, for example "blink" or "error". */
@property (nonatomic, readonly) NSString *eventType;

/** This can be used to pair events together or give them unique IDs. */
@property (nonatomic, readonly) NSString *eventId;

/** This can be used to pair events together or give them unique IDs. */
@property (nonatomic, readonly) NSString *parentId;

@end
