// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from muse_file.djinni

#import <Foundation/Foundation.h>

/**
 * @file
 * Represents all possible data type in annotation data. Those fields correspond
 * to our Muse protobuf schema, which can be found on developer website:
 * https://sites.google.com/a/interaxon.ca/muse-developer-site/data-files
 */
typedef NS_ENUM(NSInteger, IXNAnnotationFormat)
{
    IXNAnnotationFormatPlainString,
    IXNAnnotationFormatJson,
    IXNAnnotationFormatOsc,
    IXNAnnotationFormatCount,
};
