// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * @file
 * Represents data mapping in 'values' array in battery packet.
 */
typedef NS_ENUM(NSInteger, IXNBattery)
{
    /** Charge percentage remaining of battery. */
    IXNBatteryChargePercentageRemaining,
    /** Millivolts of battery from the view of the fuel gauge. */
    IXNBatteryMillivolts,
    /** Temperature in degrees Celsius. */
    IXNBatteryTemperatureCelsius,
    IXNBatteryCount,
};
