// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from muse_file.djinni

#import <Foundation/Foundation.h>

/**
 * This data structure contains fields, which describe running machine. To
 * prevent confusion, field names should correspond to names in our protobuf
 * schema: http://developer.choosemuse.com/data-files
 */

@interface IXNComputingDeviceConfiguration : NSObject
- (id)initWithComputingDeviceConfiguration:(IXNComputingDeviceConfiguration *)computingDeviceConfiguration;
- (id)initWithOsType:(NSString *)osType osVersion:(NSString *)osVersion hardwareModelName:(NSString *)hardwareModelName hardwareModelId:(NSString *)hardwareModelId processorName:(NSString *)processorName processorSpeed:(NSString *)processorSpeed numberOfProcessors:(int32_t)numberOfProcessors memorySize:(NSString *)memorySize bluetoothVersion:(NSString *)bluetoothVersion timeZone:(NSString *)timeZone timeZoneOffsetSeconds:(int32_t)timeZoneOffsetSeconds;

/** Operation system type. For ex.: "Android", "iOS", "Windows" */
@property (nonatomic, readonly) NSString *osType;

/** Operation system version. For ex.: "10.1", "4.4.2" */
@property (nonatomic, readonly) NSString *osVersion;

/** Hardware model. For ex.: "Samsung Galaxy Note 3", "Macbook Pro" */
@property (nonatomic, readonly) NSString *hardwareModelName;

/** Hardware model id. For ex.: "SM-N900W8", "MacBookPro-101" */
@property (nonatomic, readonly) NSString *hardwareModelId;

/** Processor name. For ex.: "Intel", "ARM" */
@property (nonatomic, readonly) NSString *processorName;

/** Processor frequency in Hz */
@property (nonatomic, readonly) NSString *processorSpeed;

/** Number of cores */
@property (nonatomic, readonly) int32_t numberOfProcessors;

/** Memory size. For ex.: "500MB", "2000MB" */
@property (nonatomic, readonly) NSString *memorySize;

/** Bluetooth version */
@property (nonatomic, readonly) NSString *bluetoothVersion;

/** time zone indicator */
@property (nonatomic, readonly) NSString *timeZone;

/** time zone offset in seconds */
@property (nonatomic, readonly) int32_t timeZoneOffsetSeconds;

@end
