// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * @file
 * Represents data mapping in 'values' array in DRL and REF packet.
 */
typedef NS_ENUM(NSInteger, IXNDrlRef)
{
    /** DRL sensor */
    IXNDrlRefDrl,
    /** REF sensor */
    IXNDrlRefRef,
    IXNDrlRefCount,
};
