// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * @file
 * Represents data mapping in 'values' array in EEG packet and in
 * Quantization packet.
 * Enum values correspond to head locations. Check
 * <a href="EEG lead systems">http://www.bem.fi/book/13/13.htm#03</a>
 * for details.
 */
typedef NS_ENUM(NSInteger, IXNEeg)
{
    /** Left ear */
    IXNEegTP9,
    /** Left forehead */
    IXNEegFP1,
    /** Right forehead */
    IXNEegFP2,
    /** Right ear */
    IXNEegTP10,
    IXNEegCount,
};
