// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import "IXNMuseDataPacketType.h"
#import <Foundation/Foundation.h>
@class IXNSenderInformation;

/**
 * Provides access to information about packet.
 * This packet can represent different data: eeg,
 * accelerometer, quantization, etc. Look at MuseDataPacketType enum
 * for all possible types. Look at specific type enum for information
 * 'values' field mapping.
 */

@interface IXNMuseDataPacket : NSObject
- (id)initWithMuseDataPacket:(IXNMuseDataPacket *)museDataPacket;
- (id)initWithPacketType:(IXNMuseDataPacketType)packetType timestamp:(int64_t)timestamp source:(IXNSenderInformation *)source values:(NSArray *)values;

/** Specifies what kind of values are stored in the packet. */
@property (nonatomic, readonly) IXNMuseDataPacketType packetType;

/** Microseconds since epoch (usually Jan 1, 1970). */
@property (nonatomic, readonly) int64_t timestamp;

/** Information about the %Muse which sent the packet. */
@property (nonatomic, readonly) IXNSenderInformation *source;

/**
 * Contains the actual data. Elements of the array have "double" data type.
 * Size of the array and the meaning of its elemetns depend on packet type.
 * Some types have enum which provides access to the data mapping.
 */
@property (nonatomic, readonly) NSArray *values;

@end
