// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from listeners.djinni

@class IXNMuseConnectionPacket;

/**
 * Provides abstract method to listen for changes to the current connection
 * status (like connect/disconnect). <br>
 * <B>Important:</B> DO NOT CALL connect()/disconnect() directly from
 * connection listener handler. Either create a new thread and run it from there
 * or use run_asynchronously method which creates new thread implicitly.
 */

@protocol IXNMuseConnectionListener

/**
 * Called from the Muse connection thread whenever there is a change in
 * the current connection status of the Muse the specified connection
 * event emanated from.
 */
- (void)receiveMuseConnectionPacket:(IXNMuseConnectionPacket *)packet;

@end
