// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from museinfo.djinni

#import <Foundation/Foundation.h>

/**
 * @file
 * Defines all possible Muse presets. See this link for details:
 * https://sites.google.com/a/interaxon.ca/muse-developer-site/museio/presets
 */
typedef NS_ENUM(NSInteger, IXNMusePreset)
{
    /**
     * 4 CH, 10 bit @ 220 sps, compression ON, no accelerometer, no Battery data,
     * no Error data, no DRL/REF data
     */
    IXNMusePresetPreset10,
    /**
     * 4 CH, 10 bit @ 220 sps, compression ON, 50 sps accelerometer data,
     * 01 sps Battery data, no Error data, no DRL/REF data
     */
    IXNMusePresetPreset12,
    /**
     * 4 CH, 10 bit @ 220 sps, compression ON, 50 sps accelerometer data,
     * 01 sps Battery data, real-time Error data, 10 bit @ 10 sps DRL/REF data
     * THIS PRESET IS DEFAULT
     */
    IXNMusePresetPreset14,
    IXNMusePresetCount,
};
