// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>
@class IXNSenderInformation;

/** Provides access to calculated artifacts. */

@interface IXNMuseArtifactPacket : NSObject
- (id)initWithMuseArtifactPacket:(IXNMuseArtifactPacket *)museArtifactPacket;
- (id)initWithSource:(IXNSenderInformation *)source headbandOn:(BOOL)headbandOn blink:(BOOL)blink jawClench:(BOOL)jawClench;

/** Information about %Muse which sent the packet. */
@property (nonatomic, readonly) IXNSenderInformation *source;

/**
 * Flag which represents if the %Muse Headband is on a person's head.
 * Headband On detection is one of the first things muse elements
 * algorithm does. If this flag is false you will not see other artifact
 * or bandpower data.
 */
@property (nonatomic, readonly) BOOL headbandOn;

/** Eye blinking flag. */
@property (nonatomic, readonly) BOOL blink;

/** Jaw clench flag. */
@property (nonatomic, readonly) BOOL jawClench;

@end
