// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from muse_file.djinni

#import <Foundation/Foundation.h>

/**
 * @file
 * Represents all possible protobuf message (MuseData) data types.
 * This enum corresponds to the DataType enum in protobuf schema.
 */
typedef NS_ENUM(NSInteger, IXNMessageType)
{
    IXNMessageTypeEeg,
    IXNMessageTypeQuantization,
    IXNMessageTypeAccelerometer,
    IXNMessageTypeBattery,
    IXNMessageTypeVersion,
    IXNMessageTypeConfiguration,
    IXNMessageTypeAnnotation,
    IXNMessageTypeHistogram,
    IXNMessageTypeAlgValue,
    IXNMessageTypeDsp,
    IXNMessageTypeComputingDevice,
    IXNMessageTypeEegDropped,
    IXNMessageTypeAccDropped,
    IXNMessageTypeCalmApp,
    IXNMessageTypeCalmAlg,
    IXNMessageTypeCount,
};
