// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from muse_file.djinni

#import "IXNMessageType.h"
#import "IXNMuseFile.h"
#import "IXNMuseFileReader.h"
#import <Foundation/Foundation.h>
@class IXNAnnotationData;
@class IXNComputingDeviceConfiguration;
@class IXNDspData;
@class IXNMuseConfiguration;
@class IXNMuseDataPacket;
@class IXNMuseVersion;

/**
 * Class allows to access data from 'muse' protobuf file, which could be
 * written using MuseFileWriter or another file writer, which corresponds to
 * Muse protobuf schema.
 * When file reader is created it always starts reading from the beginning
 * of the file to the end.<br>
 * <B>Threading:<B> It is NOT thread safe, you have to provide your own
 * synchronization mechanism if you plat to calls methods of this class from
 * different threads.
 */

@protocol IXNMuseFileReader

/** Returns an instance of file reader. Automatically opens a file. <br> */
+ (id <IXNMuseFileReader>)getFileReader:(id <IXNMuseFile>)file;

/**
 * Opens an existing file
 * Use this method if you explicitly closed file and want to open it again.
 * Calls Muse File open().
 */
- (void)open;

/**
 * Closes the file. Calls Muse File close().
 * You don't have to call close explicitly unless you want to close file
 * immediately. close is called automatically, when file reader object
 * is destroyed.
 */
- (void)close;

/**
 * Moves pointer to the next MuseData message in protobuf stream.<br>
 * Returns true if successful, false - if failed (reached the end of
 * stream/file).
 */
- (BOOL)gotoNextMessage;

/** Returns type of the message on current pointer position */
- (IXNMessageType)getMessageType;

/**
 * Returns id of the message on current pointer position.
 * Returns '-1' if config id isn't found in the protobuf file.
 */
- (int32_t)getMessageId;

/** Returns timestamp of the message on current pointer position. */
- (int64_t)getMessageTimestamp;

/**
 * Returns annotation structure by parsing protobuf message under
 * current pointer.<br>
 * Throws exception if current message type is not annotation.
 */
- (IXNAnnotationData *)getAnnotation;

/**
 * Returns muse configuration structure by parsing protobuf message under
 * current pointer.<br>
 * Throws exception if current message type is not muse configuration.
 */
- (IXNMuseConfiguration *)getConfiguration;

/**
 * Returns muse version structure by parsing protobuf message under
 * current pointer.<br>
 * Throws exception if current message type is not muse version.
 */
- (IXNMuseVersion *)getVersion;

/**
 * Returns computing device configuration structure by parsing protobuf
 * message under current pointer.<br>
 * Throws exception if current message type is not computing device
 * configuration.
 */
- (IXNComputingDeviceConfiguration *)getComputingDeviceConfiguration;

/**
 * Returns muse configuration structure by parsing protobuf message under
 * current pointer.<br>
 * Throws exception if current message type is not muse configuration.
 */
- (IXNDspData *)getDsp;

/**
 * Returns muse data packet by parsing protobuf message under
 * current pointer. Use this method to get EEG, Accelerometer, Battery,
 * Quantization and drooped packets.<br>
 * Throws exception if current message type is not muse data packet.
 */
- (IXNMuseDataPacket *)getDataPacket;

@end
