// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from museinfo.djinni

#import <Foundation/Foundation.h>

/**
 * @file
 * Enum defines possible power line frequencies.
 * Read this article for basic information:
 * http://en.wikipedia.org/wiki/Utility_frequency
 */
typedef NS_ENUM(NSInteger, IXNNotchFrequency)
{
    /**
     * 50 Hz frequency is used in most parts of the world:
     * Europe, Russia, Africa
     */
    IXNNotchFrequencyNotch50hz,
    /**
     * 60 Hz frequency is used in North America and Asia.
     * This is the default setting.
     */
    IXNNotchFrequencyNotch60hz,
    IXNNotchFrequencyCount,
};
